import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";

export default async function AuditReportPage({ params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return notFound();

  const client = await prisma.client.findFirst({
    where: { id: params.id, userId: session.user.id },
  });

  if (!client) return notFound();

  const audit = client.strategyAudit as {
    iva?: string;
    platform?: string;
    anchors?: string[];
    patterns?: string;
    gapReport?: string;
    updatedAt?: string;
  } | null;

  const pcr = client.pcrAudit as {
    score?: number;
    grade?: string;
    topPriority?: string;
    rewrites?: { bioHook?: string };
  } | null;

  return (
    <div className="min-h-screen bg-white text-black p-8 max-w-4xl mx-auto print:p-4">
      {/* Print button - hidden when printing */}
      <div className="mb-6 print:hidden">
        <button
          onClick={() => window.print()}
          className="px-4 py-2 bg-black text-white rounded-lg text-sm font-semibold hover:bg-gray-800 transition"
        >
          🖨️ Print / Save as PDF
        </button>
      </div>

      {/* Report header */}
      <div className="border-b-2 border-black pb-6 mb-8">
        <p className="text-xs font-mono uppercase tracking-widest text-gray-500 mb-1">Growth Diagnosis Report</p>
        <h1 className="text-3xl font-bold">{client.name}</h1>
        <div className="flex items-center gap-4 mt-2 text-sm text-gray-500">
          <span>Niche: {client.niche}</span>
          <span>·</span>
          <span>Platform: {audit?.platform?.split("\n")[0] ?? "Instagram"}</span>
          {audit?.updatedAt && <><span>·</span><span>Generated: {new Date(audit.updatedAt).toLocaleDateString()}</span></>}
        </div>
      </div>

      {/* PCR Score summary */}
      {pcr && (
        <div className="mb-8 p-5 border border-gray-200 rounded-xl">
          <h2 className="text-lg font-bold mb-3">Profile Conversion Rate (PCR)</h2>
          <div className="flex items-center gap-4">
            <div className="text-4xl font-black">{pcr.score}/100</div>
            <div>
              <div className="text-xl font-bold">Grade: {pcr.grade}</div>
              {pcr.topPriority && <p className="text-sm text-gray-600 mt-1">Priority: {pcr.topPriority}</p>}
            </div>
          </div>
          {pcr.rewrites?.bioHook && (
            <div className="mt-3 p-3 bg-gray-50 rounded-lg">
              <p className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-1">Suggested Bio Hook</p>
              <p className="text-sm italic">"{pcr.rewrites.bioHook}"</p>
            </div>
          )}
        </div>
      )}

      {/* IVA */}
      {audit?.iva && (
        <div className="mb-8">
          <h2 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">Ideal Viewer Avatar (IVA)</h2>
          <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans leading-relaxed">{audit.iva}</pre>
        </div>
      )}

      {/* Anchors */}
      {audit?.anchors && audit.anchors.length > 0 && (
        <div className="mb-8">
          <h2 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">Anchor Accounts Analyzed</h2>
          <div className="flex flex-wrap gap-2">
            {audit.anchors.map(a => (
              <span key={a} className="px-2 py-0.5 bg-gray-100 text-gray-700 text-sm rounded font-mono">{a}</span>
            ))}
          </div>
        </div>
      )}

      {/* Winning Patterns */}
      {audit?.patterns && (
        <div className="mb-8">
          <h2 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">Winning Patterns (Competitor Intelligence)</h2>
          <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans leading-relaxed">{audit.patterns}</pre>
        </div>
      )}

      {/* Gap Report */}
      {audit?.gapReport && (
        <div className="mb-8">
          <h2 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">7-Variable Gap Report</h2>
          <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans leading-relaxed">{audit.gapReport}</pre>
        </div>
      )}

      {/* Footer */}
      <div className="border-t border-gray-200 pt-4 text-xs text-gray-400 text-center">
        Generated by Instagram Analyser · {client.name} · {new Date().getFullYear()}
      </div>
    </div>
  );
}
