export const STORY_STRUCTURES = [
  { id: "heros-journey", name: "Hero's Journey", slots: ["Intro (Problem)", "Inflection Point (Pain)", "Rising Action (Failed Attempts)", "Climax (Solution Found)", "Falling Action (Results)", "Resolution (CTA)"] },
  { id: "man-in-a-hole", name: "Man in a Hole", slots: ["Comfort Zone", "Trigger (Disruption)", "Crisis & Lesson", "Recovery", "Better Place"] },
  { id: "breakthrough", name: "The Breakthrough", slots: ["Problem Statement", "Breakthrough Moment", "Fix/Takeaway Implementation"] },
  { id: "challenge-to-victory", name: "Challenge to Victory", slots: ["Doubt/Limiting Belief", "Initial Struggle", "Turning Point", "The Solution", "Transformation", "Myth Bust"] },
  { id: "transformation-snapshot", name: "Transformation Snapshot", slots: ["Before State (Pain Point)", "Low Point (Vivid Incident)", "Turning Point (Catalyst)", "After State (Outcome)", "CTA"] },
  { id: "one-decision-story", name: "One Decision Story", slots: ["Setup (The Bold Decision)", "Risk (What Could Be Lost)", "Action (How You Followed Through)", "Payoff (Incredible Outcomes)", "CTA (Challenge Audience)"] },
  { id: "mistake-and-fix", name: "Mistake & Fix", slots: ["Confession (The Mistake)", "Consequence (How Bad It Got)", "Realization (Key Insight)", "Fix (What You Did Differently)", "Result (Positive Outcomes)"] },
  { id: "failure-restart", name: "Failure/Restart", slots: ["Hook (Starting Over)", "Struggle (Costly Mistakes)", "Reveal (Top Priority)", "Steps (Beginner Roadmap)", "CTA (Skip My Mistakes)"] },
  { id: "x-to-y-journey", name: "X to Y Journey", slots: ["Start (Before Picture)", "Struggle (Daily Frustration)", "Shift (The Strategy/Habit)", "Result (After Picture)", "CTA"] },
  { id: "big-reveal", name: "Big Reveal", slots: ["Hook (Tease Secret/Truth)", "Background (Context)", "Discovery (The Reveal)", "Impact (How It Changed Things)", "CTA"] },
  { id: "lesson-from-others", name: "Lesson From Others", slots: ["Hook (Introduce Mentor/Figure)", "Situation (Their Struggle)", "Takeaway (Golden Lesson)", "Application (How You Used It)", "CTA"] },
  { id: "one-thing-i-wish", name: "One Thing I Wish I Knew", slots: ["Hook (The Knowledge)", "The Cost (Time/Money Lost)", "The Reveal (Simple Strategy)", "Proof (Results Achieved)", "CTA"] },
  { id: "arc-formula", name: "ARC Formula", slots: ["Action (Something happens)", "Reaction (How it affects things)", "Conclusion (Lesson/Takeaway)"] },
  { id: "5-line-method", name: "5-Line Method", slots: ["Line 1: Hook Statement", "Line 2: Problem/Context", "Line 3: Key Insight", "Line 4: Application", "Line 5: CTA/Payoff"] },
  { id: "5-part-arc", name: "5-Part Story Arc", slots: ["Setup", "Rising Action", "Climax/Twist", "Falling Action", "Resolution"] },
  { id: "pov-formula", name: "POV Formula", slots: ["POV Hook (Place viewer in situation)", "The Context (What's happening)", "The Conflict", "The Lesson/Realization", "The CTA"] },
  { id: "dopamine-ladder", name: "Dopamine Ladder", slots: ["Small Win (Quick hook payoff)", "Escalation (Raise the stakes)", "Tension Point", "Big Reveal/Climax", "Reward (Satisfying conclusion)"] },
];
